name: Events 
on:
  pull_request:
    types: opened
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Run a one-line script
      run: echo "This is a test for pull request events and workflow dispatch events"

